import type { HomeAssistant, RobotActivity, TaskKind } from "./types";

const translations: Record<"de" | "en", Record<string, string>> = {
  de: {
    "card.default_name": "Saugroboter",
    "card.default_dock_name": "Saugroboter-Station",
    "card.dock_name": "{name} – Station",
    "state.unavailable": "Nicht verfügbar",
    "state.offline": "Offline",
    "state.error": "Fehler",
    "state.idle": "Bereit",
    "state.docked": "An der Station",
    "state.charging": "Lädt",
    "state.charged": "Voll geladen",
    "state.cleaning": "Reinigt",
    "state.paused": "Pausiert",
    "state.returning": "Fährt zur Station",
    "state.unknown": "Status unbekannt",
    "task.vacuum": "Saugt",
    "task.mop": "Wischt",
    "task.combo": "Saugt und wischt",
    "task.unknown": "Reinigt",
    "action.start": "Starten",
    "action.pause": "Pause",
    "action.resume": "Fortsetzen",
    "action.stop": "Stoppen",
    "action.return": "Zur Station",
    "action.locate": "Orten",
    "action.programs": "Programm wählen",
    "action.confirm": "Starten",
    "action.cancel": "Abbrechen",
    "action.close": "Schließen",
    "action.details": "Details",
    "action.more_info": "Mehr Informationen",
    "section.activity": "Aktuelle Reinigung",
    "section.last_cleaning": "Letzte Reinigung",
    "section.controls": "Steuerung",
    "section.programs": "Programme",
    "section.alerts": "Hinweise",
    "section.dock": "Station",
    "section.details": "Robotereinstellungen",
    "section.maintenance": "Wartung",
    "section.map": "Karte",
    "section.diagnostics": "Technische Diagnose",
    "metric.battery": "Batterie",
    "metric.progress": "Fortschritt",
    "metric.area": "Fläche",
    "metric.duration": "Dauer",
    "metric.last_start": "Letzter Beginn",
    "metric.last_end": "Letztes Ende",
    "compact.alert_count": "{count} Hinweise",
    "compact.dock_active": "Station aktiv",
    "program.confirm_title": "Programm starten?",
    "program.confirm_text": "„{name}“ wirklich auf „{robot}“ starten?",
    "program.sent": "Anfrage für „{name}“ gesendet.",
    "program.started": "„{name}“ wurde gestartet.",
    "program.unconfirmed": "Anfrage gesendet, Start von „{name}“ nicht bestätigt.",
    "program.failed": "„{name}“ konnte nicht gestartet werden.",
    "program.pending": "Start wird angefordert …",
    "program.unavailable": "Programm ist nicht verfügbar.",
    "program.busy": "Während der aktuellen Aktivität kann kein anderes Programm gestartet werden.",
    "program.requirement_failed": "Voraussetzung „{name}“ ist nicht erfüllt.",
    "program.no_items": "Keine Programme konfiguriert.",
    "confirm.stop_title": "Reinigung stoppen?",
    "confirm.stop_text": "Die aktuelle Reinigung wird beendet und nicht automatisch fortgesetzt.",
    "confirm.return_title": "Zur Station zurückkehren?",
    "confirm.return_text": "Die aktuelle Reinigung wird für die Rückfahrt unterbrochen.",
    "confirm.switch_title": "Schalter ändern?",
    "command.failed": "Der Befehl konnte nicht ausgeführt werden.",
    "command.sent": "Befehl wurde gesendet.",
    "dock.ready": "Station bereit",
    "dock.details": "Stationsdetails",
    "dock.drying": "Mopp wird getrocknet",
    "dock.error": "Stationsfehler",
    "dock.unknown": "Status prüfen",
    "dock.unavailable": "Station nicht verfügbar",
    "dock.on": "Ein",
    "dock.off": "Aus",
    "binary.ok": "In Ordnung",
    "binary.check": "Prüfen",
    "binary.installed": "Vorhanden",
    "binary.missing": "Fehlt",
    "alert.robot_unavailable": "Roboter nicht verfügbar",
    "alert.robot_offline": "Roboter offline",
    "alert.vacuum_error": "Roboterfehler",
    "alert.dock_error": "Stationsfehler",
    "alert.water_shortage": "Wasserknappheit",
    "alert.dock_clean_water_tank": "Frischwassertank prüfen",
    "alert.dock_dirty_water_tank": "Schmutzwassertank prüfen",
    "alert.dock_cleaning_solution": "Reinigungsflüssigkeit prüfen",
    "setting.vacuum_mode": "Reinigungsmodus",
    "setting.mop_mode": "Wischmodus",
    "setting.mop_intensity": "Wischintensität",
    "setting.volume": "Lautstärke",
    "setting.emptying_mode": "Entleerungsmodus",
    "setting.child_lock": "Kindersicherung",
    "diagnostic.switch_aria": "{name}: {action}",
    "diagnostic.raw_state": "Rohzustand",
    "diagnostic.last_changed": "Geändert",
    "action.turn_on": "einschalten",
    "action.turn_off": "ausschalten",
    "config.warning.duplicate_program": "Das doppelte Programm „{value}“ wurde nur einmal übernommen.",
    "config.warning.duplicate_section": "Der doppelte Abschnitt „{value}“ wurde nur einmal übernommen.",
    "maintenance.remaining": "Verbleibend",
    "maintenance.alert_summary": "{count} Wartungshinweise",
    "maintenance.most_urgent": "Am dringendsten: {name} · {value}",
    "common.unknown": "Unbekannt",
    "common.unavailable": "Nicht verfügbar",
    "common.warning": "Warnung",
    "common.critical": "Kritisch",
  },
  en: {
    "card.default_name": "Vacuum",
    "card.default_dock_name": "Vacuum dock",
    "card.dock_name": "{name} – Dock",
    "state.unavailable": "Unavailable",
    "state.offline": "Offline",
    "state.error": "Error",
    "state.idle": "Ready",
    "state.docked": "Docked",
    "state.charging": "Charging",
    "state.charged": "Fully charged",
    "state.cleaning": "Cleaning",
    "state.paused": "Paused",
    "state.returning": "Returning to dock",
    "state.unknown": "Status unknown",
    "task.vacuum": "Vacuuming",
    "task.mop": "Mopping",
    "task.combo": "Vacuuming and mopping",
    "task.unknown": "Cleaning",
    "action.start": "Start",
    "action.pause": "Pause",
    "action.resume": "Resume",
    "action.stop": "Stop",
    "action.return": "Return to dock",
    "action.locate": "Locate",
    "action.programs": "Choose program",
    "action.confirm": "Start",
    "action.cancel": "Cancel",
    "action.close": "Close",
    "action.details": "Details",
    "action.more_info": "More information",
    "section.activity": "Current cleaning",
    "section.last_cleaning": "Last cleaning",
    "section.controls": "Controls",
    "section.programs": "Programs",
    "section.alerts": "Notices",
    "section.dock": "Dock",
    "section.details": "Robot settings",
    "section.maintenance": "Maintenance",
    "section.map": "Map",
    "section.diagnostics": "Technical diagnostics",
    "metric.battery": "Battery",
    "metric.progress": "Progress",
    "metric.area": "Area",
    "metric.duration": "Duration",
    "metric.last_start": "Last start",
    "metric.last_end": "Last end",
    "compact.alert_count": "{count} notices",
    "compact.dock_active": "Dock active",
    "program.confirm_title": "Start program?",
    "program.confirm_text": "Start “{name}” on “{robot}” now?",
    "program.sent": "Request for “{name}” sent.",
    "program.started": "“{name}” started.",
    "program.unconfirmed": "Request sent, but start of “{name}” was not confirmed.",
    "program.failed": "“{name}” could not be started.",
    "program.pending": "Requesting start …",
    "program.unavailable": "Program is unavailable.",
    "program.busy": "Another program cannot be started during the current activity.",
    "program.requirement_failed": "Requirement “{name}” is not met.",
    "program.no_items": "No programs configured.",
    "confirm.stop_title": "Stop cleaning?",
    "confirm.stop_text": "The current cleaning will end and will not resume automatically.",
    "confirm.return_title": "Return to dock?",
    "confirm.return_text": "The current cleaning will be interrupted for the return trip.",
    "confirm.switch_title": "Change switch?",
    "command.failed": "The command could not be performed.",
    "command.sent": "Command sent.",
    "dock.ready": "Dock ready",
    "dock.details": "Dock details",
    "dock.drying": "Mop is drying",
    "dock.error": "Dock error",
    "dock.unknown": "Check status",
    "dock.unavailable": "Dock unavailable",
    "dock.on": "On",
    "dock.off": "Off",
    "binary.ok": "OK",
    "binary.check": "Check",
    "binary.installed": "Installed",
    "binary.missing": "Missing",
    "alert.robot_unavailable": "Robot unavailable",
    "alert.robot_offline": "Robot offline",
    "alert.vacuum_error": "Robot error",
    "alert.dock_error": "Dock error",
    "alert.water_shortage": "Water shortage",
    "alert.dock_clean_water_tank": "Check clean-water tank",
    "alert.dock_dirty_water_tank": "Check dirty-water tank",
    "alert.dock_cleaning_solution": "Check cleaning solution",
    "setting.vacuum_mode": "Cleaning mode",
    "setting.mop_mode": "Mop mode",
    "setting.mop_intensity": "Mop intensity",
    "setting.volume": "Volume",
    "setting.emptying_mode": "Emptying mode",
    "setting.child_lock": "Child lock",
    "diagnostic.switch_aria": "{name}: {action}",
    "diagnostic.raw_state": "Raw state",
    "diagnostic.last_changed": "Changed",
    "action.turn_on": "turn on",
    "action.turn_off": "turn off",
    "config.warning.duplicate_program": "The duplicate program “{value}” was included only once.",
    "config.warning.duplicate_section": "The duplicate section “{value}” was included only once.",
    "maintenance.remaining": "Remaining",
    "maintenance.alert_summary": "{count} maintenance notices",
    "maintenance.most_urgent": "Most urgent: {name} · {value}",
    "common.unknown": "Unknown",
    "common.unavailable": "Unavailable",
    "common.warning": "Warning",
    "common.critical": "Critical",
  },
};

export function languageOf(hass?: HomeAssistant): "de" | "en" {
  const requested = hass?.locale?.language ?? hass?.language ?? "en";
  return requested.toLowerCase().startsWith("de") ? "de" : "en";
}

export function localize(
  hass: HomeAssistant | undefined,
  key: string,
  replacements?: Record<string, string | number>,
): string {
  const language = languageOf(hass);
  let result = translations[language][key] ?? translations.en[key] ?? key;
  for (const [name, value] of Object.entries(replacements ?? {})) {
    result = result.replaceAll(`{${name}}`, String(value));
  }
  return result;
}

export function activityLabel(hass: HomeAssistant | undefined, activity: RobotActivity): string {
  return localize(hass, `state.${activity}`);
}

export function taskLabel(hass: HomeAssistant | undefined, kind: TaskKind): string {
  return localize(hass, `task.${kind}`);
}
